"""BTS candidate search and ranking for GeoSignal AI.

Candidate coordinates are selected from the analysis grid, filtered using
the high-canopy constraint, validated against precomputed LOS records, and
ranked using the expected Coverage Score improvement of surrounding cells.

This module never performs live DEM LOS computation. It consumes records
previously generated by ``geosignal.los.precompute_los_grid``.
"""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Iterable, Mapping, Sequence
from typing import Any

import numpy as np
from sklearn.neighbors import BallTree

from geosignal.confidence import tag_confidence
from geosignal.constraints import is_high_canopy
from geosignal.models import (
    CONSOLIDATED_FEATURES,
    BTSCandidate,
    ConfidenceThresholds,
    InsufficientCandidatesResult,
)


EARTH_RADIUS_M: float = 6_371_008.8
_COORDINATE_PRECISION: int = 7


def rank_bts_candidates(
    grid_cells: np.ndarray,
    coverage_scores: np.ndarray,
    land_cover_classes: np.ndarray,
    canopy_heights_m: np.ndarray,
    *,
    los_records: Iterable[Mapping[str, Any]],
    shap_values_by_cell: Sequence[Mapping[str, float]],
    region_id: str,
    target_area_id: str,
    model_version: str,
    scoring_run_id: str,
    nearest_opencellid_km: Sequence[float | None] | None = None,
    nearest_ookla_km: Sequence[float | None] | None = None,
    n_candidates: int = 10,
    signal_radius_m: float = 10_000.0,
    exclude_high_canopy: bool = True,
    confidence_thresholds: ConfidenceThresholds | None = None,
) -> list[BTSCandidate] | InsufficientCandidatesResult:
    """Return ranked BTS candidates for a target area.

    Parameters
    ----------
    grid_cells:
        ``(N, 2)`` array in ``(latitude, longitude)`` order. These cells must
        already have been filtered to the active TargetArea.

    coverage_scores:
        Current Coverage Score per grid cell in the inclusive range 0–100.

    land_cover_classes:
        ESA WorldCover class code per grid cell.

    canopy_heights_m:
        Canopy height in metres per grid cell.

    los_records:
        Precomputed records produced by ``precompute_los_grid`` or read from
        Supabase ``los_results``. A coordinate without an LOS record is never
        emitted as a candidate.

    shap_values_by_cell:
        Full eight-feature SHAP or AHP-attribution dictionary per grid cell.

    region_id:
        Active region identifier, such as ``"ntt"``.

    target_area_id:
        Target area used in ``InsufficientCandidatesResult``.

    model_version:
        Version identifier assigned to the scoring model.

    scoring_run_id:
        Identifier of the active scoring run.

    nearest_opencellid_km / nearest_ookla_km:
        Source-proximity distances aligned with ``grid_cells``. When omitted,
        the canonical confidence tagger treats the source as absent and
        assigns Low confidence.

    n_candidates:
        Maximum candidates returned. Must be at least two.

    signal_radius_m:
        Radius used by BallTree to find surrounding cells whose current
        coverage deficit contributes to expected improvement.

    Returns
    -------
    list[BTSCandidate] | InsufficientCandidatesResult
        Ranked candidates when at least two survive filtering; otherwise an
        explicit insufficient-candidates result.

    Notes
    -----
    Until the full what-if simulation is implemented in Task 18, expected
    improvement is represented by the mean remaining score deficit
    ``100 - current_score`` among LOS-clear surrounding cells. Task 18 will
    later compute the detailed per-cell scenario deltas.
    """
    coordinates = _validate_grid_cells(grid_cells)
    count = len(coordinates)

    scores = _validate_numeric_vector(
        coverage_scores,
        name="coverage_scores",
        expected_length=count,
    )
    land_cover = _validate_integer_vector(
        land_cover_classes,
        name="land_cover_classes",
        expected_length=count,
    )
    canopy = _validate_numeric_vector(
        canopy_heights_m,
        name="canopy_heights_m",
        expected_length=count,
    )

    if np.any((scores < 0.0) | (scores > 100.0)):
        raise ValueError("coverage_scores must be within [0, 100]")

    if np.any(canopy < 0.0):
        raise ValueError("canopy_heights_m cannot contain negative values")

    if not region_id.strip():
        raise ValueError("region_id cannot be empty")

    if not target_area_id.strip():
        raise ValueError("target_area_id cannot be empty")

    if not model_version.strip():
        raise ValueError("model_version cannot be empty")

    if not scoring_run_id.strip():
        raise ValueError("scoring_run_id cannot be empty")

    if n_candidates < 2:
        raise ValueError("n_candidates must be at least 2")

    if signal_radius_m <= 0:
        raise ValueError("signal_radius_m must be positive")

    if len(shap_values_by_cell) != count:
        raise ValueError(
            "shap_values_by_cell must have the same length as grid_cells"
        )

    validated_shap = [
        _validate_shap_values(values)
        for values in shap_values_by_cell
    ]

    ocid_distances = _validate_optional_distance_vector(
        nearest_opencellid_km,
        expected_length=count,
        name="nearest_opencellid_km",
    )
    ookla_distances = _validate_optional_distance_vector(
        nearest_ookla_km,
        expected_length=count,
        name="nearest_ookla_km",
    )

    thresholds = (
        confidence_thresholds
        if confidence_thresholds is not None
        else ConfidenceThresholds()
    )

    los_index = _build_los_index(
        los_records=los_records,
        region_id=region_id,
    )

    spatial_index = BallTree(
        np.radians(coordinates),
        metric="haversine",
    )
    radius_radians = signal_radius_m / EARTH_RADIUS_M

    surviving: list[dict[str, Any]] = []

    for cell_index, coordinate in enumerate(coordinates):
        point = (
            float(coordinate[0]),
            float(coordinate[1]),
        )

        if exclude_high_canopy and is_high_canopy(
            land_cover_class=int(land_cover[cell_index]),
            canopy_height_m=float(canopy[cell_index]),
        ):
            continue

        candidate_key = _coordinate_key(*point)

        # Requirement 4.4 / Task 12.2:
        # no precomputed LOS result means no candidate is emitted.
        if candidate_key not in los_index:
            continue

        candidate_los = los_index[candidate_key]

        neighbour_indices = spatial_index.query_radius(
            np.radians(coordinate.reshape(1, -1)),
            r=radius_radians,
            return_distance=False,
        )[0]

        los_clear_neighbours: list[int] = []

        for neighbour_index_raw in neighbour_indices:
            neighbour_index = int(neighbour_index_raw)
            neighbour = coordinates[neighbour_index]

            neighbour_key = _coordinate_key(
                float(neighbour[0]),
                float(neighbour[1]),
            )

            if candidate_los.get(neighbour_key) is True:
                los_clear_neighbours.append(neighbour_index)

        if los_clear_neighbours:
            clear_scores = scores[
                np.asarray(los_clear_neighbours, dtype=int)
            ]

            remaining_deficit = np.maximum(
                0.0,
                100.0 - clear_scores,
            )

            expected_improvement = float(
                np.mean(remaining_deficit)
            )
        else:
            # LOS was computed, but no clear path exists to any cell in
            # the active radius. Keep the validated candidate with zero
            # benefit rather than inventing an improvement.
            expected_improvement = 0.0

        confidence = tag_confidence(
            point=point,
            nearest_opencellid_km=ocid_distances[cell_index],
            nearest_ookla_km=ookla_distances[cell_index],
            thresholds=thresholds,
        )

        surviving.append(
            {
                "coordinate": point,
                "expected_improvement": expected_improvement,
                "confidence_tag": confidence,
                "shap_values": validated_shap[cell_index],
                "source_index": cell_index,
            }
        )

    if len(surviving) < 2:
        reason = (
            "No candidates survived canopy and precomputed LOS filters."
            if len(surviving) == 0
            else (
                "Only one candidate survived canopy and precomputed "
                "LOS filters."
            )
        )

        return InsufficientCandidatesResult(
            surviving_count=len(surviving),
            reason=reason,
            target_area_id=target_area_id,
        )

    # Deterministic ordering:
    # 1. largest improvement first
    # 2. latitude
    # 3. longitude
    # 4. original grid index
    surviving.sort(
        key=lambda item: (
            -item["expected_improvement"],
            item["coordinate"][0],
            item["coordinate"][1],
            item["source_index"],
        )
    )

    selected = surviving[:n_candidates]

    return [
        BTSCandidate(
            coordinate=item["coordinate"],
            expected_improvement=item["expected_improvement"],
            los_validated=True,
            confidence_tag=item["confidence_tag"],
            shap_values=item["shap_values"],
            rank=rank,
            model_version=model_version,
            scoring_run_id=scoring_run_id,
        )
        for rank, item in enumerate(selected, start=1)
    ]


def _build_los_index(
    los_records: Iterable[Mapping[str, Any]],
    region_id: str,
) -> dict[
    tuple[float, float],
    dict[tuple[float, float], bool],
]:
    """Build candidate → target-cell LOS lookup from database records."""
    index: dict[
        tuple[float, float],
        dict[tuple[float, float], bool],
    ] = defaultdict(dict)

    required_fields = {
        "region_id",
        "candidate_lat",
        "candidate_lon",
        "cell_lat",
        "cell_lon",
        "los_clear",
    }

    for record in los_records:
        missing = required_fields.difference(record.keys())

        if missing:
            missing_names = ", ".join(sorted(missing))
            raise ValueError(
                f"LOS record is missing required fields: {missing_names}"
            )

        if str(record["region_id"]) != region_id:
            continue

        candidate_key = _coordinate_key(
            float(record["candidate_lat"]),
            float(record["candidate_lon"]),
        )
        cell_key = _coordinate_key(
            float(record["cell_lat"]),
            float(record["cell_lon"]),
        )

        los_clear_value = record["los_clear"]

        if not isinstance(los_clear_value, (bool, np.bool_)):
            raise ValueError("los_clear must be a boolean")

        # Duplicate candidate-cell records may occur after repeated batch
        # exports. A clear result is retained if any duplicate says True.
        previous = index[candidate_key].get(cell_key, False)
        index[candidate_key][cell_key] = (
            previous or bool(los_clear_value)
        )

    return dict(index)


def _coordinate_key(
    latitude: float,
    longitude: float,
) -> tuple[float, float]:
    """Create a stable lookup key for floating-point coordinates."""
    return (
        round(latitude, _COORDINATE_PRECISION),
        round(longitude, _COORDINATE_PRECISION),
    )


def _validate_grid_cells(grid_cells: np.ndarray) -> np.ndarray:
    coordinates = np.asarray(grid_cells, dtype=np.float64)

    if coordinates.ndim != 2 or coordinates.shape[1] != 2:
        raise ValueError("grid_cells must have shape (N, 2)")

    if not np.isfinite(coordinates).all():
        raise ValueError("grid_cells must contain only finite values")

    if np.any(
        (coordinates[:, 0] < -90.0)
        | (coordinates[:, 0] > 90.0)
    ):
        raise ValueError("grid_cells contains invalid latitude values")

    if np.any(
        (coordinates[:, 1] < -180.0)
        | (coordinates[:, 1] > 180.0)
    ):
        raise ValueError("grid_cells contains invalid longitude values")

    return coordinates


def _validate_numeric_vector(
    values: np.ndarray,
    *,
    name: str,
    expected_length: int,
) -> np.ndarray:
    vector = np.asarray(values, dtype=np.float64)

    if vector.ndim != 1:
        raise ValueError(f"{name} must be one-dimensional")

    if len(vector) != expected_length:
        raise ValueError(
            f"{name} must have the same length as grid_cells"
        )

    if not np.isfinite(vector).all():
        raise ValueError(f"{name} must contain only finite values")

    return vector


def _validate_integer_vector(
    values: np.ndarray,
    *,
    name: str,
    expected_length: int,
) -> np.ndarray:
    raw = np.asarray(values)

    if raw.ndim != 1:
        raise ValueError(f"{name} must be one-dimensional")

    if len(raw) != expected_length:
        raise ValueError(
            f"{name} must have the same length as grid_cells"
        )

    numeric = raw.astype(np.float64)

    if not np.isfinite(numeric).all():
        raise ValueError(f"{name} must contain only finite values")

    if not np.equal(numeric, np.floor(numeric)).all():
        raise ValueError(f"{name} must contain integer values")

    return numeric.astype(np.int64)


def _validate_optional_distance_vector(
    values: Sequence[float | None] | None,
    *,
    expected_length: int,
    name: str,
) -> list[float | None]:
    if values is None:
        return [None] * expected_length

    vector = list(values)

    if len(vector) != expected_length:
        raise ValueError(
            f"{name} must have the same length as grid_cells"
        )

    validated: list[float | None] = []

    for value in vector:
        if value is None:
            validated.append(None)
            continue

        numeric = float(value)

        if np.isnan(numeric):
            raise ValueError(f"{name} cannot contain NaN")

        if numeric < 0:
            raise ValueError(
                f"{name} cannot contain negative values"
            )

        # Infinity is the canonical "source absent" marker accepted by
        # tag_confidence.
        validated.append(numeric)

    return validated


def _validate_shap_values(
    shap_values: Mapping[str, float],
) -> dict[str, float]:
    expected = set(CONSOLIDATED_FEATURES)
    actual = set(shap_values.keys())

    if actual != expected:
        missing = expected.difference(actual)
        extra = actual.difference(expected)

        details: list[str] = []

        if missing:
            details.append(
                f"missing={sorted(missing)}"
            )

        if extra:
            details.append(
                f"extra={sorted(extra)}"
            )

        raise ValueError(
            "Each SHAP dictionary must contain exactly the eight "
            f"CONSOLIDATED_FEATURES ({'; '.join(details)})"
        )

    result = {
        feature: float(shap_values[feature])
        for feature in CONSOLIDATED_FEATURES
    }

    if not np.isfinite(list(result.values())).all():
        raise ValueError("SHAP values must all be finite")

    return result